// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package state

import (
	"fmt"
)

const (
	// Closed is a State of type Closed.
	Closed State = iota
	// Open is a State of type Open.
	Open
	// HalfOpen is a State of type HalfOpen.
	HalfOpen
)

const _StateName = "ClosedOpenHalfOpen"

var _StateMap = map[State]string{
	Closed:   _StateName[0:6],
	Open:     _StateName[6:10],
	HalfOpen: _StateName[10:18],
}

// String implements the Stringer interface.
func (x State) String() string {
	if str, ok := _StateMap[x]; ok {
		return str
	}
	return fmt.Sprintf("State(%d)", x)
}

var _StateValue = map[string]State{
	_StateName[0:6]:   Closed,
	_StateName[6:10]:  Open,
	_StateName[10:18]: HalfOpen,
}

// ParseState attempts to convert a string to a State
func ParseState(name string) (State, error) {
	if x, ok := _StateValue[name]; ok {
		return x, nil
	}
	return State(0), fmt.Errorf("%s is not a valid State", name)
}
